/* Cartões de repetição espaçada (SM-2). `a` é a frente, `b` o verso, `tema` casa com a taxonomia.
   Regra editorial: o verso traz o número e a diretriz que o sustenta — cartão sem âncora vira boato. */
window.FLASH=[
{"tema":"cardio","a":"Escore CHA₂DS₂-VA: o que mudou em relação ao CHA₂DS₂-VASc?","b":"A ESC 2024 retirou o ponto atribuído ao sexo feminino. Máximo passou a 8. Anticoagular é classe I com escore ≥2 e classe IIa com escore 1."},
{"tema":"cardio","a":"Infarto com supra de ST: qual o tempo que define fibrinólise em vez de angioplastia primária?","b":"Se o tempo previsto até a angioplastia primária for maior que 120 minutos, fibrinolisar e transferir para estratégia fármaco-invasiva (coronariografia em 2 a 24 h)."},
{"tema":"pneumo","a":"Crise asmática: a partir de que saturação se oferta oxigênio e qual o alvo?","b":"GINA 2026: oxigênio só se saturação abaixo de 92%; alvo de 93% a 95% em adultos, adolescentes e crianças de 6 a 11 anos. Hiperóxia piora a troca gasosa."},
{"tema":"pneumo","a":"Asma com anafilaxia: o que vem primeiro?","b":"GINA 2026: adrenalina intramuscular ANTES do broncodilatador. É a única droga que trata broncoespasmo, hipotensão e edema ao mesmo tempo."},
{"tema":"pneumo","a":"DPOC: quantas exacerbações justificam escalonar a terapia inalatória?","b":"GOLD 2026 baixou o limiar: UMA exacerbação moderada já indica escalonar. Eosinófilos acima de 300/µL sustentam acrescentar corticoide inalatório."},
{"tema":"pneumo","a":"DPOC: a partir de que idade se recomenda a vacina contra o VSR?","b":"GOLD 2026 reduziu de 60 para 50 anos. Não há proteção cruzada com a vacina da influenza."},
{"tema":"emergencias","a":"Choque séptico: qual a pressão arterial média alvo no paciente com 65 anos ou mais?","b":"Surviving Sepsis 2026: faixa de 60 a 65 mmHg, em vez de alvos mais altos. No adulto em geral, alvo inicial de 65 mmHg."},
{"tema":"emergencias","a":"Como administrar betalactâmico na manutenção do choque séptico?","b":"Surviving Sepsis 2026 recomenda infusão PROLONGADA na manutenção, após a dose de ataque em bolus. Eficácia depende do tempo acima da CIM."},
{"tema":"emergencias","a":"O lactato deve ser usado como meta de infusão de volume?","b":"Não. A diretriz de 2026 sugere lactato seriado para acompanhar tendência, mas a fluidoterapia após o bolus inicial é individualizada — não se infunde volume até normalizar o lactato."},
{"tema":"nefro","a":"Quando indicar inibidor de SGLT2 na doença renal crônica sem diabetes?","b":"KDIGO 2024: TFG ≥20 mL/min/1,73 m² com relação albumina-creatinina ≥200 mg/g (1A), ou insuficiência cardíaca independentemente da albuminúria."},
{"tema":"nefro","a":"Albuminúria persistente apesar de bloqueio do SRAA e iSGLT2 no diabetes tipo 2: o que acrescentar?","b":"Antagonista mineralocorticoide NÃO esteroidal (finerenona), com monitorização do potássio antes e depois do início."},
{"tema":"nefro","a":"Alcalose metabólica: como o cloro urinário separa as causas?","b":"Cloro urinário abaixo de 20 mEq/L = responsiva ao cloro (vômito, diurético) → repor salina com potássio. Acima de 20 = resistente ao cloro (excesso de mineralocorticoide)."},
{"tema":"neuro","a":"Dose da tenecteplase no AVC isquêmico agudo e como ela se compara à alteplase?","b":"AHA/ASA 2026: 0,25 mg/kg, máximo de 25 mg, aceita como alternativa plena à alteplase (0,9 mg/kg, máximo 90 mg) na janela de até 4,5 horas."},
{"tema":"neuro","a":"AVC ao despertar: o que autoriza trombolisar?","b":"Ressonância com lesão na difusão SEM contrapartida no FLAIR indica lesão provavelmente com menos de 4,5 horas — critério de seleção da AHA/ASA 2026."},
{"tema":"neuro","a":"NIHSS de 0 a 5 contraindica trombólise?","b":"Não. A AHA/ASA 2026 formaliza que o escore baixo isoladamente não deve decidir contra trombolisar; o que pesa é se o déficit é incapacitante para aquele paciente."},
{"tema":"endocrino","a":"Diabetes tipo 2 com doença renal: a escolha do hipoglicemiante depende da hemoglobina glicada?","b":"Não. ADA 2026 e KDIGO 2024: indica-se a classe com benefício cardiorrenal (iSGLT2, agonista de GLP-1) independentemente da glicada."},
{"tema":"endocrino","a":"Agonista de GLP-1 no diabetes tipo 1: pode?","b":"ADA 2026 passou a recomendar considerá-lo em pessoas com diabetes tipo 1 e obesidade, junto da insulina, com dose individualizada — a dose mais eficaz pode não ser a maior aprovada."},
{"tema":"endocrino","a":"Monitorização contínua de glicose exige uso de insulina?","b":"ADA 2026: não. Recomenda-se considerar o sensor já no diagnóstico e a qualquer momento depois, para melhorar desfechos do manejo."}
];
