/* Índice das leituras (resumos de estudo em leituras/*.html).
   `area` liga a leitura ao tema do banco e alimenta o botão "treinar questões" ao final do texto.
   Itens com `grupo` são separadores de seção.
   `min` é estimado em ritmo de estudo (~80 palavras/min), não de leitura corrida. */
window.LEITURAS=[

 {grupo:"Cardiologia", sub:"as diretrizes que mais mudaram"},
 {f:"fibrilacao-atrial.html", tipo:"ESC 2024 · integral", area:"cardio", min:26,
  t:"Fibrilação atrial: o caminho AF-CARE da ESC 2024",
  s:"Os quatro domínios do cuidado, o escore que perdeu o ponto por sexo, a tabela de doses dos anticoagulantes com critérios de redução, as três proibições classe III e a ablação promovida a primeira linha."},
 {f:"sindromes-coronarianas.html", tipo:"ACC/AHA 2025 · integral", area:"cardio", min:20,
  t:"Síndromes coronarianas agudas: a diretriz de 2025",
  s:"Os relógios da reperfusão, ticagrelor e prasugrel à frente do clopidogrel, oxigênio fora da rotina, revascularização completa — e por que ela não vale no choque cardiogênico."},
 {f:"hipertensao.html", tipo:"SBC/SBH/SBN 2025 · integral", area:"cardio", min:19,
  t:"Hipertensão arterial: a diretriz brasileira de 2025",
  s:"120/80 virou pré-hipertensão, a meta passou a ser abaixo de 130/80 para todos os hipertensos e o tratamento começa com dois fármacos na maioria dos pacientes."},
 {f:"insuficiencia-cardiaca.html", tipo:"ESC 2026", area:"cardio", min:11,
  t:"Insuficiência cardíaca: o que a diretriz de 2026 mudou",
  s:"O fenótipo de fração levemente reduzida deixou de existir, os quatro estágios, os quatro pilares e a entrada dos análogos de GLP-1 na fração preservada com obesidade."},
 {f:"taquiarritmias.html", tipo:"ESC 2019 e 2022", area:"cardio", min:17,
  t:"Taquiarritmias: do QRS estreito ao largo",
  s:"As duas perguntas que ordenam a conduta, a técnica correta da adenosina, por que QRS largo é taquicardia ventricular até prova em contrário e a armadilha da fibrilação atrial pré-excitada."},
 {f:"valvopatias.html", tipo:"ESC/EACTS e ACC/AHA", area:"cardio", min:20,
  t:"Valvopatias: o sintoma é o gatilho da cirurgia",
  s:"Ler o sopro, a tríade que muda o prognóstico na estenose aórtica, os limiares de função ventricular na insuficiência mitral e aórtica, próteses e por que o anticoagulante direto é proibido na mecânica."},
 {f:"hipertensao-secundaria.html", tipo:"SBC 2025 e ESC 2024", area:"cardio", min:21,
  t:"Hipertensão resistente e secundária: quando parar de acrescentar fármaco",
  s:"Pseudorresistência antes de tudo, a medida correta da pressão, a espironolactona como quarto fármaco, os erros que anulam o rastreio de hiperaldosteronismo e urgência × emergência."},
 {f:"cardiomiopatias.html", tipo:"ESC 2023/2025 e AHA/ACC", area:"cardio", min:20,
  t:"Cardiomiopatias, miocardite e pericárdio",
  s:"O sopro que muda com a manobra na hipertrófica, parede espessa com baixa voltagem = infiltração, Chagas, periparto, takotsubo, restrição de exercício na miocardite e constritiva × restritiva."},

 {grupo:"O paciente instável", sub:"o que precisa estar automático"},
 {f:"choque-septico.html", tipo:"Surviving Sepsis 2026", area:"emergencias", min:12,
  t:"Choque séptico: da suspeita à primeira hora",
  s:"O que mudou em 2026: alvo pressórico no idoso, infusão prolongada de betalactâmico, descalonamento como recomendação e o fim do lactato como meta de volume."},
 {f:"parada-cardiaca.html", tipo:"AHA 2025 · integral", area:"emergencias", min:15,
  t:"Parada cardiorrespiratória: suporte avançado na AHA 2025",
  s:"O momento da adrenalina muda com o ritmo, cálcio, bicarbonato e magnésio saíram do algoritmo de rotina, e entraram desfibrilação sequencial dupla, RCP com cabeça elevada e ultrassom."},
 {f:"choque.html", tipo:"ESICM 2025 · integral", area:"emergencias", min:15,
  t:"Choque circulatório: monitorização segundo a ESICM 2025",
  s:"O enchimento capilar virou recomendação formal, a saturação venosa central e a Pv-aCO₂ entram juntas, e o alvo de pressão deixou de ser um número único — 80 mmHg no traumatismo craniano."},
 {f:"sdra.html", tipo:"Definição global 2024", area:"emergencias", min:15,
  t:"SDRA: a definição global de 2024 e o que fazer com ela",
  s:"Cateter nasal de alto fluxo passou a contar, a oximetria substitui a gasometria (SpO₂/FiO₂ <315), o ultrassom vale como imagem — e a ventilação protetora com peso predito."},
 {f:"intoxicacoes.html", tipo:"AACT/EAPCCT e MS", area:"emergencias", min:19,
  t:"Intoxicações: síndromes tóxicas, antídotos e o que não fazer",
  s:"As seis síndromes pelo exame físico, a tabela de antídotos, os dois gaps que diagnosticam metanol, o que sobrou da descontaminação — e os acidentes por animais peçonhentos."},

 {grupo:"Endocrinologia e metabologia", sub:"a área que mais mudou de lógica"},
 {f:"diabetes-tipo2.html", tipo:"ADA 2026 + SBD", area:"endocrino", min:27,
  t:"Diabetes tipo 2: a escolha do segundo fármaco deixou de ser pela glicemia",
  s:"A árvore de decisão por comorbidade, as novidades de 2026 (GLP-1 no tipo 1 com obesidade, MASLD com fibrose, CGM desde o diagnóstico), superbasalização e o rastreio que começa no dia do diagnóstico."},
 {f:"emergencias-glicemicas.html", tipo:"Consenso ADA/EASD 2024", area:"endocrino", min:23,
  t:"Cetoacidose e estado hiperosmolar: as três coisas que se fazem juntas",
  s:"Por que o potássio decide se a insulina entra agora, o beta-hidroxibutirato que substituiu a cetonúria, a cetoacidose euglicêmica do SGLT2 e o erro de suspender a insulina quando a glicemia normaliza."},
 {f:"tireoide.html", tipo:"ATA e SBEM", area:"endocrino", min:23,
  t:"Tireoide: os cinco cenários que o clínico resolve",
  s:"Quando não pedir TSH, os erros de absorção da levotiroxina, a pergunta que separa hipertireoidismo de tireoidite, a ordem dos fármacos na crise tireotóxica e o nódulo que dispensa punção."},
 {f:"adrenal-hipofise.html", tipo:"Endocrine Society", area:"endocrino", min:24,
  t:"Adrenal e hipófise: quando o exame vem antes e quando vem depois",
  s:"Crise adrenal tratada antes de confirmar, as duas etapas do Cushing, o hiperaldosteronismo subrastreado, o alfabloqueio que precede o beta no feocromocitoma e o efeito gancho da prolactina."},

 {grupo:"Hematologia", sub:"do hemograma à emergência"},
 {f:"anemias.html", tipo:"Abordagem sistemática", area:"hemato", min:25,
  t:"Anemias: o VCM organiza, mas quem decide é o ferro e o reticulócito",
  s:"A tabela que separa ferropriva, inflamação e talassemia, o ferro em dias alternados, o folato que mascara a deficiência de B12, os esquizócitos que são emergência e o alvo transfusional restritivo."},
 {f:"hemostasia.html", tipo:"ASH e ISTH", area:"hemato", min:21,
  t:"Hemostasia: plaquetopenias, anticoagulação e as reversões",
  s:"As duas plaquetopenias que trombam e em que transfundir plaqueta piora, o teste da mistura, a tabela de reversão de cada anticoagulante e por que a ponte com heparina caiu em desuso."},
 {f:"neoplasias-hematologicas.html", tipo:"OMS 2022 e NCCN", area:"hemato", min:22,
  t:"Leucemias, linfomas e mieloma: o que o clínico tem de reconhecer",
  s:"O corticoide que inviabiliza a biópsia, a promielocítica que mata em horas, a punção que não diagnostica linfoma, a cintilografia que sai negativa no mieloma e as emergências hematológicas."},
 {f:"transfusao-hemoterapia.html", tipo:"AABB e RDC 34/2014", area:"hemato", min:19,
  t:"Transfusão e reações transfusionais",
  s:"Gatilho restritivo e uma unidade por vez, quando plaqueta faz mal, o plasma que não reverte varfarina, irradiado × filtrado × lavado e o par TRALI × TACO."},
 {f:"hemoglobinopatias.html", tipo:"PCDT Ministério da Saúde e ASH", area:"hemato", min:20,
  t:"Doença falciforme e talassemias",
  s:"A crise dolorosa como emergência com relógio, a síndrome torácica que aparece no terceiro dia, o Doppler transcraniano que evita AVC, hidroxiureia para todos e a microcitose que não é ferropenia."},

 {grupo:"Reumatologia", sub:"quando o órgão define o tratamento"},
 {f:"artrite-reumatoide.html", tipo:"EULAR 2025", area:"reumato", min:21,
  t:"Artrite reumatoide: a janela de oportunidade e as 9 recomendações da EULAR 2025",
  s:"Metotrexato cedo com corticoide só como ponte, o alerta de segurança dos inibidores de JAK, o rastreio obrigatório antes do imunobiológico e o risco cardiovascular que se multiplica por 1,5."},
 {f:"lupus-vasculites.html", tipo:"EULAR e ACR", area:"reumato", min:23,
  t:"Lúpus e vasculites: quando o órgão define o tratamento",
  s:"O FAN que não é rastreio, a hidroxicloroquina para todos, a biópsia que define a classe da nefrite, a síndrome antifosfolípide que não aceita anticoagulante direto e a síndrome pulmão-rim."},
 {f:"cristais-espondilo.html", tipo:"ACR e ASAS-EULAR", area:"reumato", min:20,
  t:"Artrites por cristais, espondiloartrites e a monoartrite aguda",
  s:"Toda monoartrite é séptica até prova em contrário, uricemia normal não exclui gota, o alvo de urato com profilaxia, a lombalgia que melhora com exercício e por que metotrexato não serve no eixo."},
 {f:"sjogren-esclerose-miopatias.html", tipo:"EULAR/ACR e SBR", area:"reumato", min:20,
  t:"Sjögren, esclerose sistêmica e miopatias inflamatórias",
  s:"A crise renal esclerodérmica que o corticoide precipita, o captopril mantido com creatinina subindo, o rastreio anual de hipertensão pulmonar, anti-MDA5 e a miosite que não responde a imunossupressão."},
 {f:"dor-musculoesqueletica.html", tipo:"EULAR, ACP e SBR", area:"reumato", min:21,
  t:"Dor musculoesquelética, fibromialgia e lombalgia",
  s:"Dor nociceptiva, neuropática e nociplástica; as bandeiras vermelhas da lombalgia e por que imagem precoce piora; exercício como primeira linha; e o que nunca usar na fibromialgia."},

 {grupo:"Pneumologia", sub:"diretrizes de 2026"},
 {f:"dpoc.html", tipo:"GOLD 2026", area:"pneumo", min:19,
  t:"DPOC: o que o GOLD 2026 mudou",
  s:"Uma única exacerbação moderada já pesa para escalonar, os eosinófilos que decidem o corticoide inalatório, o alvo de saturação de 88 a 92% e o que realmente reduz mortalidade."},
 {f:"asma.html", tipo:"GINA 2026", area:"pneumo", min:18,
  t:"Asma: o GINA 2026 e o fim do broncodilatador isolado",
  s:"As estratégias AIR e MART, os quatro novos fluxogramas de exacerbação, o limiar de oxigênio que caiu para 92% e a diferença entre asma difícil de tratar e asma grave."},
 {f:"tromboembolismo.html", tipo:"AHA/ACC 2026 · integral", area:"pneumo", min:19,
  t:"Embolia pulmonar: as categorias A a E da diretriz de 2026",
  s:"A classificação clínica que aposentou maciço e submaciço, quem recebe alta do pronto-socorro, quando a terapia avançada entra e a pergunta de seguimento que quase ninguém faz."},
 {f:"pneumonia-duracao.html", tipo:"ATS 2025", area:"pneumo", min:8,
  t:"Pneumonia comunitária: o antibiótico ficou mais curto",
  s:"Menos de cinco dias para quem atinge estabilidade clínica, cinco ou mais na apresentação grave — e por que a radiografia não decide a duração."},
 {f:"doencas-intersticiais.html", tipo:"ATS/ERS e Fleischner", area:"pneumo", min:20,
  t:"Doenças intersticiais e o nódulo pulmonar",
  s:"Crepitação em velcro e difusão baixa, o padrão que dispensa biópsia, o corticoide que aumentou mortalidade na fibrose idiopática, fenótipo progressivo e o seguimento do nódulo incidental."},
 {f:"hipertensao-pulmonar-sono.html", tipo:"ESC/ERS 2022 e AASM", area:"pneumo", min:19,
  t:"Hipertensão pulmonar e distúrbios respiratórios do sono",
  s:"A pressão de oclusão que separa grupo 1 de grupo 2, a cintilografia V/Q que a angiotomografia não substitui, a única forma curável, CPAP e o oxigênio que piora a hipoventilação."},

 {grupo:"Infectologia", sub:"o que é competência do clínico"},
 {f:"hiv.html", tipo:"PCDT do MS", area:"infecto", min:21,
  t:"HIV: tratar todos, no mesmo dia, e o que rastrear conforme o CD4",
  s:"As duas exclusões antes do início imediato, indetectável igual a intransmissível, as profilaxias por faixa de CD4, a pressão de abertura na criptococose e o tempo do antirretroviral na tuberculose."},
 {f:"tuberculose.html", tipo:"Manual do MS", area:"infecto", min:19,
  t:"Tuberculose: do sintomático respiratório à hepatotoxicidade",
  s:"O teste rápido molecular como primeiro exame, o esquema básico e as fases, quando suspender e como reintroduzir de forma escalonada, e quem trata infecção latente."},
 {f:"antimicrobianos.html", tipo:"IDSA e ANVISA", area:"infecto", min:18,
  t:"Antimicrobianos: escolher, descalonar e parar",
  s:"Colonização não é infecção, a tabela de espectro e de resistência, os cursos curtos que igualam os longos, a desrotulação da alergia à penicilina e a profilaxia cirúrgica que termina na sala."},
 {f:"dengue.html", tipo:"Manual do MS 2024", area:"infecto", min:12,
  t:"Dengue: a fase crítica começa quando a febre cede",
  s:"Grupos A a D, os sete sinais de alarme e os volumes exatos — 10 mL/kg na primeira hora no grupo C, 20 mL/kg em 20 minutos no D, começando onde o paciente estiver."},
 {f:"febre-origem-indeterminada.html", tipo:"ESC 2023 e IDSA", area:"infecto", min:20,
  t:"Febre de origem indeterminada e endocardite",
  s:"As quatro grandes causas e o roteiro em etapas, por que não tratar às cegas, três pares de hemocultura antes do antibiótico, os critérios de Duke de 2023 e quando operar."},
 {f:"infeccoes-tropicais.html", tipo:"Ministério da Saúde e OPAS", area:"infecto", min:24,
  t:"Arboviroses, malária e endemias brasileiras",
  s:"O estadiamento A-B-C-D da dengue e a hidratação de cada grupo, a malária que agrava em horas, leptospirose com hemorragia alveolar, Chagas oral, calazar e febre maculosa."},

 {grupo:"Neurologia", sub:"as decisões com relógio"},
 {f:"avc-isquemico.html", tipo:"AHA/ASA 2026", area:"neuro", min:11,
  t:"AVC isquêmico agudo: a janela e as decisões",
  s:"Tenecteplase como alternativa plena, o que fazer com NIHSS baixo, o AVC ao despertar e os limites de pressão antes de trombolisar."},
 {f:"epilepsia.html", tipo:"ILAE e NCS/AES", area:"neuro", min:20,
  t:"Crise convulsiva e estado de mal: o relógio dos cinco minutos",
  s:"A subdose do benzodiazepínico que define o desfecho, o algoritmo por tempo, o estado de mal não convulsivo que se disfarça de pós-ictal e o valproato na mulher em idade fértil."},
 {f:"cefaleias.html", tipo:"ICHD-3 e AHS", area:"neuro", min:20,
  t:"Cefaleias: separar a primária da que mata",
  s:"Os sinais de alarme, a cefaleia em trovoada com tomografia normal, a aura que contraindica o contraceptivo combinado, a profilaxia a partir de 4 dias e a cefaleia por uso excessivo."},
 {f:"demencias-parkinson.html", tipo:"NIA-AA, MDS e ABN", area:"neuro", min:21,
  t:"Demências e parkinsonismos: reconhecer o padrão antes de tratar",
  s:"As causas reversíveis, a hipersensibilidade a neurolépticos nos corpos de Lewy, a hidrocefalia de pressão normal, o parkinsonismo medicamentoso e as neuropatias periféricas."},

 {grupo:"Nefrologia", sub:"aguda e crônica"},
 {f:"eletrolitos.html", tipo:"Abordagem sistemática", area:"nefro", min:16,
  t:"Distúrbios hidroeletrolíticos e ácido-base",
  s:"Ler a gasometria em seis passos, o delta-delta que revela o distúrbio triplo, o cloro urinário na alcalose, os limites de correção do sódio e a sequência da hipercalemia."},
 {f:"lesao-renal-aguda.html", tipo:"KDIGO", area:"nefro", min:19,
  t:"Lesão renal aguda: as três perguntas e as cinco indicações de diálise",
  s:"Pré-renal, renal ou pós-renal; o sedimento e os índices que enganam sob diurético; a tríplice ameaça; e por que diurético e dopamina não tratam."},
 {f:"drc.html", tipo:"KDIGO 2024", area:"nefro", min:19,
  t:"Doença renal crônica: a albuminúria é metade do diagnóstico",
  s:"A classificação em duas dimensões, os pilares que reduzem progressão, a elevação esperada de 30% da creatinina, o alvo restrito de hemoglobina e o preparo precoce para diálise."},
 {f:"glomerulopatias.html", tipo:"KDIGO 2021/2024", area:"nefro", min:18,
  t:"Glomerulopatias: nefrítica, nefrótica e a que corre",
  s:"O sedimento urinário que fecha o diagnóstico, o diferencial pelo complemento, a rapidamente progressiva como emergência e as indicações de biópsia."},
 {f:"nefrolitiase-itu.html", tipo:"EAU, AUA e IDSA", area:"nefro", min:18,
  t:"Litíase urinária e infecção do trato urinário",
  s:"Cólica renal e terapia expulsiva, obstrução com infecção = drenagem de urgência, os tipos de cálculo e a bacteriúria assintomática que não se trata."},

 {grupo:"Gastroenterologia e hepatologia", sub:"do sangramento ao fígado"},
 {f:"cirrose.html", tipo:"Baveno VII e EASL", area:"gastro", min:15,
  t:"Cirrose descompensada: as cinco complicações que matam",
  s:"A regra dos 5 da elastografia, o pacote da hemorragia varicosa, os 250 neutrófilos da peritonite, a albumina que reduz mortalidade e por que dosar amônia não ajuda."},
 {f:"hemorragia-digestiva.html", tipo:"ESGE, ACG e Baveno VII", area:"gastro", min:17,
  t:"Hemorragia digestiva: estabilizar, estratificar, endoscopar",
  s:"Por que transfundir menos, a hematoquezia que é sangramento alto, a classificação de Forrest e o antibiótico no cirrótico que reduz mortalidade tanto quanto a endoscopia."},
 {f:"pancreatite-vias-biliares.html", tipo:"AGA e Tokyo Guidelines", area:"gastro", min:18,
  t:"Pancreatite e vias biliares: o que decide nas primeiras 24 horas",
  s:"Nutrição enteral precoce, nenhum antibiótico profilático, colecistectomia na mesma internação — e a colangite obstrutiva que exige drenagem, não só antibiótico."},
 {f:"dii.html", tipo:"ECCO e AGA", area:"gastro", min:17,
  t:"Doenças inflamatórias intestinais: Crohn e retocolite",
  s:"O corticoide que induz mas nunca mantém, os critérios de Truelove e Witts, a profilaxia de trombose com sangramento intestinal e a estenose fibrótica que não responde a biológico."},
 {f:"hepatites-masld.html", tipo:"PCDT do MS, EASL e AASLD", area:"gastro", min:20,
  t:"Hepatites virais e doença hepática esteatótica metabólica",
  s:"Ler a sorologia da hepatite B, o anti-HBc que ninguém pede antes do rituximabe, a hepatite C curável em 8 a 12 semanas e a MASLD em que o que importa é a fibrose."},
 {f:"disfagia-esofago.html", tipo:"ACG e Chicago 4.0", area:"gastro", min:20,
  t:"Disfagia, refluxo e doenças do esôfago",
  s:"Orofaríngea × esofágica, o padrão que aponta a causa, o inibidor de bomba tomado na hora certa, o Barrett e sua vigilância, esofagite eosinofílica e acalasia."},
 {f:"diarreia-ma-absorcao.html", tipo:"ACG e AGA", area:"gastro", min:21,
  t:"Diarreia crônica e síndromes de má absorção",
  s:"Aquosa, gordurosa ou inflamatória; a diarreia noturna que muda tudo; celíaca que se esconde na anemia; colite microscópica na biópsia de mucosa normal; e os sais biliares esquecidos."},

 {grupo:"Oncologia", sub:"reconhecer e rastrear"},
 {f:"emergencias-oncologicas.html", tipo:"ASCO, ESMO e NCCN", area:"onco", min:21,
  t:"Emergências oncológicas: as sete que não podem esperar o oncologista",
  s:"A primeira hora da neutropenia febril, a compressão medular cujo prognóstico é o estado neurológico agora, a lise tumoral e a toxicidade da imunoterapia, que se trata com imunossupressão."},
 {f:"rastreamento-cancer.html", tipo:"INCA e USPSTF", area:"onco", min:21,
  t:"Rastreamento de câncer: o que o Brasil recomenda e por que difere",
  s:"Os três vieses que fazem o rastreio parecer melhor do que é, a divergência entre INCA e sociedades na mama, a decisão compartilhada na próstata e quando parar de rastrear."},

 {grupo:"Geriatria e cuidados paliativos", sub:"o idoso não se apresenta pelo órgão"},
 {f:"sindromes-geriatricas.html", tipo:"AGS e World Falls Guidelines", area:"geriatria", min:21,
  t:"Síndromes geriátricas: os cinco is e a avaliação que muda conduta",
  s:"As atividades instrumentais que falham primeiro, a avaliação multifatorial das quedas, o delirium hipoativo, a cascata de prescrição e as metas terapêuticas do idoso frágil."},
 {f:"paliativos.html", tipo:"CFM e OMS", area:"geriatria", min:18,
  t:"Cuidados paliativos: decisões que o clínico toma",
  s:"A pergunta surpresa, o protocolo de má notícia em seis passos, a escada analgésica com rotação de opioide, o opioide na dispneia e as distinções entre ortotanásia, distanásia e eutanásia."},

 {grupo:"Psiquiatria e dermatologia na clínica", sub:"as duas que o clínico resolve"},
 {f:"depressao-ansiedade.html", tipo:"APA, NICE e MS", area:"psiq", min:23,
  t:"Depressão, ansiedade e risco de suicídio no consultório do clínico",
  s:"A pergunta sobre mania antes de todo antidepressivo, escolher o fármaco pelo perfil, perguntar sobre suicídio não induz, e a desprescrição do benzodiazepínico no idoso."},
 {f:"psicose-agitacao-substancias.html", tipo:"Project BETA e APA", area:"psiq", min:22,
  t:"Psicose, agitação e substâncias: a emergência psiquiátrica é clínica até prova em contrário",
  s:"As bandeiras vermelhas de causa orgânica, o desescalonamento antes da contenção, síndrome neuroléptica maligna × serotoninérgica, o lítio e a abstinência alcoólica."},
 {f:"derma-clinica.html", tipo:"Consensos internacionais", area:"derma", min:21,
  t:"Dermatologia para o clínico: a pele que anuncia doença grave",
  s:"Os sinais que separam o exantema banal da farmacodermia que mata, DRESS e necrólise epidérmica, a pele como sinal de doença sistêmica, as úlceras de membros e a lesão pigmentada."},

 {grupo:"SUS, ética e epidemiologia", sub:"o que cai e quase ninguém estuda"},
 {f:"sus-principios.html", tipo:"Lei 8.080, PNAB e MS", area:"sus", min:21,
  t:"SUS: os princípios, a atenção primária e os números que a prova cobra",
  s:"Princípios e legislação, os quatro atributos da atenção primária, notificação compulsória — e epidemiologia clínica em uma página: sensibilidade, valor preditivo, NNT e intervalo de confiança."},
 {f:"etica-medica.html", tipo:"CFM e legislação", area:"sus", min:21,
  t:"Ética médica: sigilo, consentimento, documentos e o fim da vida",
  s:"Quem decide, o que pode ser dito, o que se assina — atestado, prontuário, declaração de óbito — e as distinções entre ortotanásia, distanásia, eutanásia e sedação paliativa."},

 {grupo:"Doenças raras", sub:"individualmente raras, coletivamente comuns"},
 {f:"raras-abordagem.html", tipo:"Política Nacional e ACMG", area:"sus", min:21,
  t:"Doenças raras: quando o clínico deve desconfiar",
  s:"As sete bandeiras vermelhas, os padrões clínicos que se repetem, o heredograma de três gerações, a variante de significado incerto que não é diagnóstico e as raras que têm tratamento."},
 {f:"raras-deposito-metabolicas.html", tipo:"PCDT e consensos", area:"endocrino", min:23,
  t:"Doenças de depósito e metabólicas do adulto",
  s:"Fabry, Gaucher, Pompe tardia, Wilson, hemocromatose, alfa-1-antitripsina, porfirias, homocistinúria e mitocondriais — cada uma com o exame que diagnostica e o erro que se comete."},
 {f:"raras-sistemicas.html", tipo:"Consensos internacionais", area:"reumato", min:25,
  t:"Raras sistêmicas: amiloidose, sarcoidose, IgG4, HLH e as febres periódicas",
  s:"Tipar o amiloide antes de tratar, a sarcoidose que nem sempre se trata, a IgG4 que imita câncer, a ferritina acima de 10.000 que é HLH, Behçet, mastocitose e imunodeficiência do adulto."}
];
