/* Índice das leituras (resumos de estudo em leituras/*.html).
   `area` liga a leitura ao tema do banco e alimenta o botão "treinar questões" ao final do texto.
   Itens com `grupo` são separadores de seção.
   `min` é estimado em ritmo de estudo (~80 palavras/min), não de leitura corrida. */
window.LEITURAS=[

 {grupo:"Cardiologia", sub:"as diretrizes que mais mudaram"},
 {f:"fibrilacao-atrial.html", tipo:"ESC 2024 · monografia", area:"cardio", min:75,
  t:"Fibrilação atrial: o caminho AF-CARE da ESC 2024",
  s:"A diretriz europeia de 2024 inteira, na ordem em que ela pensa o paciente: os quatro domínios do AF-CARE, o CHA₂DS₂-VA sem o ponto do sexo, a tabela de doses dos anticoagulantes diretos com os critérios de redução de cada um e as recomendações classe III que nomeiam como erro a subdose, o antiagregante somado e o escore de sangramento usado para não anticoagular. Traz também a janela que encolheu de 48 para 24 horas na cardioversão, o controle de frequência com doses e a ablação promovida a primeira linha na fibrilação paroxística."},
 {f:"sindromes-coronarianas.html", tipo:"ACC/AHA 2025 · monografia", area:"cardio", min:89,
  t:"Síndromes coronarianas agudas",
  s:"A diretriz ACC/AHA 2025 que uniu infarto com e sem supra num só documento, percorrida na ordem do atendimento: ECG em 10 minutos e as derivações que faltam, troponina no caminho 0/1 h, os relógios de 90 e 120 minutos, fibrinólise e estratégia fármaco-invasiva, antiplaquetários e anticoagulantes por cenário com doses, revascularização completa e a exceção do choque, complicações mecânicas, lípides, transfusão e alta. Classe e nível transcritos da fonte, 7 ECGs comentados — inclusive precordiais direitas e o padrão de De Winter — e 3 fluxogramas."},
 {f:"hipertensao.html", tipo:"SBC 2025 e AHA/ACC 2025 · monografia", area:"cardio", min:76,
  t:"Hipertensão arterial: a diretriz brasileira de 2025 e onde ela diverge da americana",
  s:"A régua brasileira inteira: pré-hipertensão a partir de 120/80, meta única de <130/80, início com dois fármacos na maioria, doses das cinco classes, escalada até a espironolactona e os alvos da emergência hipertensiva por cenário. Em cada tema, o ponto exato em que a AHA/ACC 2025 diz outra coisa — que é onde a prova gosta de bater. Inclui técnica de medida, cortes de MAPA e MRPA, avental branco e mascarada, gestação e o idoso frágil."},
 {f:"insuficiencia-cardiaca.html", tipo:"ESC 2026", area:"cardio", min:11,
  t:"Insuficiência cardíaca: o que a diretriz de 2026 mudou",
  s:"O fenótipo de fração levemente reduzida deixou de existir, os quatro estágios, os quatro pilares e a entrada dos análogos de GLP-1 na fração preservada com obesidade."},
 {f:"taquiarritmias.html", tipo:"ESC 2019 · monografia", area:"cardio", min:74,
  t:"Taquiarritmias: do QRS estreito ao largo",
  s:"A diretriz europeia de taquicardia supraventricular do começo ao fim: as duas perguntas que ordenam a conduta, Valsalva modificada do REVERT, adenosina e o que a pausa revela, reentrada nodal, ortodrômica e antidrômica, taquicardia atrial focal e multifocal, flutter e seus circuitos. No QRS largo, os critérios de diferenciação e por que é TV até prova em contrário — com o que é proibido na fibrilação atrial pré-excitada. Classes e níveis transcritos da fonte, 6 ECGs e 2 fluxogramas."},
 {f:"valvopatias.html", tipo:"ESC/EACTS e ACC/AHA", area:"cardio", min:20,
  t:"Valvopatias: o sintoma é o gatilho da cirurgia",
  s:"Ler o sopro, a tríade que muda o prognóstico na estenose aórtica, os limiares de função ventricular na insuficiência mitral e aórtica, próteses e por que o anticoagulante direto é proibido na mecânica."},
 {f:"hipertensao-secundaria.html", tipo:"SBC 2025 e ESC 2024", area:"cardio", min:21,
  t:"Hipertensão resistente e secundária: quando parar de acrescentar fármaco",
  s:"Pseudorresistência antes de tudo, a medida correta da pressão, a espironolactona como quarto fármaco, os erros que anulam o rastreio de hiperaldosteronismo e urgência × emergência."},
 {f:"cardiomiopatias.html", tipo:"ESC 2023/2025 e AHA/ACC", area:"cardio", min:20,
  t:"Cardiomiopatias, miocardite e pericárdio",
  s:"O sopro que muda com a manobra na hipertrófica, parede espessa com baixa voltagem = infiltração, Chagas, periparto, takotsubo, restrição de exercício na miocardite e constritiva × restritiva."},
 {f:"bradiarritmias-e-marcapasso.html", tipo:"ACC/AHA/HRS 2018 · monografia", area:"cardio", min:69,
  t:"Bradiarritmias e distúrbios de condução: da atropina ao marca-passo",
  s:"Três perguntas resolvem quase todo caso — instável, causa reversível, nodal ou infranodal — e é a terceira que separa observar de implantar. Cobre disfunção do nó sinusal, os graus de bloqueio com as definições exatas da diretriz, as manobras que localizam o nível, o tratamento agudo com doses e por que a atropina falha no infranodal, a bradicardia do infarto inferior contra a do anterior, e as indicações de marca-passo com classe — incluindo a assimetria que a prova cobra: no infranodal, dispositivo independentemente de sintoma; na disfunção sinusal, nada sem sintoma correlacionado."},
 {f:"arritmias-ventriculares.html", tipo:"ESC 2022 · monografia", area:"cardio", min:78,
  t:"Arritmias ventriculares e prevenção de morte súbita",
  s:"Da extrassístole isolada ao cardiodesfibrilador: quando a carga de extrassístoles vira miocardiopatia, manejo agudo da TV sustentada e da tempestade elétrica, e o risco por substrato — isquêmico, dilatada, hipertrófica, arritmogênica de VD, sarcoidose e Chagas. Canalopatias com o gatilho e o tratamento de cada uma, critérios e classe do CDI em prevenção primária e secundária, papel da ressonância e do estudo eletrofisiológico, e o rastreio da família do sobrevivente. 4 ECGs e 3 fluxogramas."},

 {grupo:"O paciente instável", sub:"o que precisa estar automático"},
 {f:"dor-toracica.html", tipo:"Abordagem sindrômica · 2021–2026", area:"emergencias", min:45,
  t:"Dor torácica aguda: abordagem sindrômica no pronto-socorro",
  s:"Os seis diagnósticos que matam em horas organizados pela decisão: ECG em 10 minutos, troponina ultrassensível em caminho de decisão, ADD-RS antes do D-dímero na aorta, PERC e D-dímero ajustado à idade na embolia, e o que autoriza alta com MACE abaixo de 1%. Fluxograma de triagem."},
 {f:"choque-septico.html", tipo:"Surviving Sepsis Campaign 2026 · monografia", area:"emergencias", min:69,
  t:"Sepse e choque séptico: a Surviving Sepsis Campaign 2026",
  s:"As 129 declarações de 2026 organizadas pelo relógio da primeira hora: rastreio sem qSOFA, cultura antes do antibiótico e o preço exato de atrasá-la, tempo até a primeira dose por grau de certeza diagnóstica, infusão prolongada de betalactâmico e descalonamento agora fortes, 30 mL/kg, noradrenalina periférica e a faixa de 60 a 65 mmHg no idoso. Fecha com o que mudou desde 2021 e as condutas contra as quais a diretriz se posicionou."},
 {f:"parada-cardiaca.html", tipo:"AHA 2025 · monografia", area:"emergencias", min:67,
  t:"Parada cardiorrespiratória no adulto: suporte avançado de vida",
  s:"A Parte 9 de 2025 inteira, com classe e nível: quando a adrenalina entra em cada ritmo, cálcio e bicarbonato em classe 3, a FV que não cede a três choques, o CO₂ expirado que não decide sozinho, as regras de término por escopo de prática, e as taquicardias e bradicardias peri-parada com doses. Quatro fluxogramas."},
 {f:"choque.html", tipo:"ESICM 2025 · monografia", area:"emergencias", min:62,
  t:"Choque circulatório: diagnóstico, monitorização e primeiras decisões",
  s:"As cinquenta declarações da ESICM 2025 postas em ordem de uso: hipotensão que não define, as três janelas e o enchimento capilar, Pv-aCO₂ acima de 6, o alvo de pressão por população (65–70 no séptico, ≥80 no TCE, sistólica 80–90 no trauma sangrando), elevação passiva das pernas com recomendação forte, VPP e veia cava isoladas proibidas, a escada de monitorização até o cateter de artéria pulmonar. Três fluxogramas."},
 {f:"sdra.html", tipo:"Definição global 2024 e ATS 2024 · monografia", area:"emergencias", min:70,
  t:"SDRA: a definição global de 2024 e o tratamento que muda desfecho",
  s:"O que a definição global de 2024 mudou em relação a Berlim — alto fluxo, oximetria, ultrassom e o ambiente de poucos recursos — e o que fazer com o diagnóstico: peso predito e volume corrente, platô, PEEP, pressão de distensão e transpulmonar, prona, bloqueio neuromuscular, ECMO venovenosa, balanço hídrico e corticoide, com força e certeza da diretriz da ATS de 2024."},
 {f:"intoxicacoes.html", tipo:"AACT/EAPCCT e MS", area:"emergencias", min:19,
  t:"Intoxicações: síndromes tóxicas, antídotos e o que não fazer",
  s:"As seis síndromes pelo exame físico, a tabela de antídotos, os dois gaps que diagnosticam metanol, o que sobrou da descontaminação — e os acidentes por animais peçonhentos."},
 {f:"via-aerea-e-intubacao.html", tipo:"DAS, ATLS 11 e AHA 2025", area:"emergencias", min:21,
  t:"Via aérea e sequência rápida de intubação",
  s:"Quando intubar de verdade, os preditores de dificuldade, a hemodinâmica que se otimiza ANTES de induzir, a droga certa para cada choque, a capnografia que não mente e o plano de resgate."},
 {f:"ventilacao-mecanica.html", tipo:"ATS/ESICM/SCCM 2023 e AMIB", area:"emergencias", min:23,
  t:"Ventilação mecânica: do ajuste inicial ao desmame",
  s:"Peso predito, platô e pressão de distensão; o ajuste por fenótipo; a autoPEEP e o teste da desconexão; as assincronias que se resolvem sem sedar mais; e o desmame protocolado."},
 {f:"sedacao-analgesia-delirium.html", tipo:"PADIS 2018 e pacote ABCDEF", area:"emergencias", min:21,
  t:"Sedação, analgesia e delirium na terapia intensiva",
  s:"Analgesia primeiro e sedação leve, o alvo de RASS escrito, a síndrome da infusão do propofol, o delirium hipoativo que ninguém vê e o pacote que reduz mortalidade."},
 {f:"politraumatizado.html", tipo:"ATLS 11ª edição", area:"emergencias", min:22,
  t:"Abordagem inicial ao politraumatizado",
  s:"O ABCDE e por que a ordem existe, as seis lesões torácicas que matam, os cinco lugares onde o sangue se esconde, a reanimação hemostática e a tríade letal."},
 {f:"nutricao-do-paciente-critico.html", tipo:"ESPEN 2023 e ASPEN/SCCM", area:"emergencias", min:22,
  t:"Nutrição e metabolismo no paciente crítico",
  s:"Por que ofertar menos na fase aguda, as calorias escondidas do propofol, o vasopressor que não contraindica dieta, a síndrome de realimentação e a proteína que não se restringe."},

 {grupo:"Endocrinologia e metabologia", sub:"a área que mais mudou de lógica"},
 {f:"diabetes-tipo2.html", tipo:"ADA 2026 + SBD", area:"endocrino", min:27,
  t:"Diabetes tipo 2: a escolha do segundo fármaco deixou de ser pela glicemia",
  s:"A árvore de decisão por comorbidade, as novidades de 2026 (GLP-1 no tipo 1 com obesidade, MASLD com fibrose, CGM desde o diagnóstico), superbasalização e o rastreio que começa no dia do diagnóstico."},
 {f:"emergencias-glicemicas.html", tipo:"Consenso ADA/EASD 2024", area:"endocrino", min:23,
  t:"Cetoacidose e estado hiperosmolar: as três coisas que se fazem juntas",
  s:"Por que o potássio decide se a insulina entra agora, o beta-hidroxibutirato que substituiu a cetonúria, a cetoacidose euglicêmica do SGLT2 e o erro de suspender a insulina quando a glicemia normaliza."},
 {f:"tireoide.html", tipo:"ATA e SBEM", area:"endocrino", min:23,
  t:"Tireoide: os cinco cenários que o clínico resolve",
  s:"Quando não pedir TSH, os erros de absorção da levotiroxina, a pergunta que separa hipertireoidismo de tireoidite, a ordem dos fármacos na crise tireotóxica e o nódulo que dispensa punção."},
 {f:"adrenal-hipofise.html", tipo:"Endocrine Society", area:"endocrino", min:24,
  t:"Adrenal e hipófise: quando o exame vem antes e quando vem depois",
  s:"Crise adrenal tratada antes de confirmar, as duas etapas do Cushing, o hiperaldosteronismo subrastreado, o alfabloqueio que precede o beta no feocromocitoma e o efeito gancho da prolactina."},

 {grupo:"Hematologia", sub:"do hemograma à emergência"},
 {f:"anemias.html", tipo:"Abordagem sistemática", area:"hemato", min:25,
  t:"Anemias: o VCM organiza, mas quem decide é o ferro e o reticulócito",
  s:"A tabela que separa ferropriva, inflamação e talassemia, o ferro em dias alternados, o folato que mascara a deficiência de B12, os esquizócitos que são emergência e o alvo transfusional restritivo."},
 {f:"hemostasia.html", tipo:"ASH e ISTH", area:"hemato", min:21,
  t:"Hemostasia: plaquetopenias, anticoagulação e as reversões",
  s:"As duas plaquetopenias que trombam e em que transfundir plaqueta piora, o teste da mistura, a tabela de reversão de cada anticoagulante e por que a ponte com heparina caiu em desuso."},
 {f:"neoplasias-hematologicas.html", tipo:"OMS 2022 e NCCN", area:"hemato", min:22,
  t:"Leucemias, linfomas e mieloma: o que o clínico tem de reconhecer",
  s:"O corticoide que inviabiliza a biópsia, a promielocítica que mata em horas, a punção que não diagnostica linfoma, a cintilografia que sai negativa no mieloma e as emergências hematológicas."},
 {f:"transfusao-hemoterapia.html", tipo:"AABB e RDC 34/2014", area:"hemato", min:19,
  t:"Transfusão e reações transfusionais",
  s:"Gatilho restritivo e uma unidade por vez, quando plaqueta faz mal, o plasma que não reverte varfarina, irradiado × filtrado × lavado e o par TRALI × TACO."},
 {f:"hemoglobinopatias.html", tipo:"PCDT Ministério da Saúde e ASH", area:"hemato", min:20,
  t:"Doença falciforme e talassemias",
  s:"A crise dolorosa como emergência com relógio, a síndrome torácica que aparece no terceiro dia, o Doppler transcraniano que evita AVC, hidroxiureia para todos e a microcitose que não é ferropenia."},

 {grupo:"Reumatologia", sub:"quando o órgão define o tratamento"},
 {f:"artrite-reumatoide.html", tipo:"EULAR 2025", area:"reumato", min:21,
  t:"Artrite reumatoide: a janela de oportunidade e as 9 recomendações da EULAR 2025",
  s:"Metotrexato cedo com corticoide só como ponte, o alerta de segurança dos inibidores de JAK, o rastreio obrigatório antes do imunobiológico e o risco cardiovascular que se multiplica por 1,5."},
 {f:"lupus-vasculites.html", tipo:"EULAR e ACR", area:"reumato", min:23,
  t:"Lúpus e vasculites: quando o órgão define o tratamento",
  s:"O FAN que não é rastreio, a hidroxicloroquina para todos, a biópsia que define a classe da nefrite, a síndrome antifosfolípide que não aceita anticoagulante direto e a síndrome pulmão-rim."},
 {f:"cristais-espondilo.html", tipo:"ACR e ASAS-EULAR", area:"reumato", min:20,
  t:"Artrites por cristais, espondiloartrites e a monoartrite aguda",
  s:"Toda monoartrite é séptica até prova em contrário, uricemia normal não exclui gota, o alvo de urato com profilaxia, a lombalgia que melhora com exercício e por que metotrexato não serve no eixo."},
 {f:"sjogren-esclerose-miopatias.html", tipo:"EULAR/ACR e SBR", area:"reumato", min:20,
  t:"Sjögren, esclerose sistêmica e miopatias inflamatórias",
  s:"A crise renal esclerodérmica que o corticoide precipita, o captopril mantido com creatinina subindo, o rastreio anual de hipertensão pulmonar, anti-MDA5 e a miosite que não responde a imunossupressão."},
 {f:"dor-musculoesqueletica.html", tipo:"EULAR, ACP e SBR", area:"reumato", min:21,
  t:"Dor musculoesquelética, fibromialgia e lombalgia",
  s:"Dor nociceptiva, neuropática e nociplástica; as bandeiras vermelhas da lombalgia e por que imagem precoce piora; exercício como primeira linha; e o que nunca usar na fibromialgia."},

 {grupo:"Pneumologia", sub:"diretrizes de 2026"},
 {f:"radiografia-torax.html", tipo:"Fleischner 2024 · monografia", area:"pneumo", min:89,
  t:"Radiografia de tórax: o que o clínico precisa saber",
  s:"A leitura que se faz à beira do leito antes do laudo: os quatro controles de qualidade que impedem laudo falso, a varredura ABCDE, o sinal da silhueta que localiza a consolidação sem tomografia, os cinco padrões com o vocabulário da Fleischner Society, o pneumotórax que no paciente deitado não vai para o ápice, o ar livre que só aparece de pé, tubos e cateteres com as medidas, e os números que dizem quando a radiografia NÃO basta — 43% de sensibilidade para pneumonia, 40% para pneumotórax, 19% das descompensações cardíacas sem congestão. Vinte e duas figuras — treze esquemas próprios e nove radiografias comentadas — e três fluxogramas."},
 {f:"dpoc.html", tipo:"GOLD 2026", area:"pneumo", min:19,
  t:"DPOC: o que o GOLD 2026 mudou",
  s:"Uma única exacerbação moderada já pesa para escalonar, os eosinófilos que decidem o corticoide inalatório, o alvo de saturação de 88 a 92% e o que realmente reduz mortalidade."},
 {f:"asma.html", tipo:"GINA 2026", area:"pneumo", min:18,
  t:"Asma: o GINA 2026 e o fim do broncodilatador isolado",
  s:"As estratégias AIR e MART, os quatro novos fluxogramas de exacerbação, o limiar de oxigênio que caiu para 92% e a diferença entre asma difícil de tratar e asma grave."},
 {f:"tromboembolismo.html", tipo:"AHA/ACC 2026 · monografia", area:"pneumo", min:75,
  t:"Tromboembolismo pulmonar agudo: diagnóstico, categorias A a E e tratamento",
  s:"A diretriz americana de 2026 aposentou maciço, submaciço e não maciço e criou cinco categorias clínicas, A a E, com modificador respiratório. O texto vai da probabilidade pré-teste (Wells, Genebra revisado, PERC) e do D-dímero ajustado à idade e do YEARS até trombólise, cateter, trombectomia, ECMO, filtro de cava, duração da anticoagulação e HPTEC — com classe e nível transcritos da fonte, três fluxogramas e as tabelas de pontos dos escores."},
 {f:"pneumonia-duracao.html", tipo:"ATS 2025", area:"pneumo", min:8,
  t:"Pneumonia comunitária: o antibiótico ficou mais curto",
  s:"Menos de cinco dias para quem atinge estabilidade clínica, cinco ou mais na apresentação grave — e por que a radiografia não decide a duração."},
 {f:"doencas-intersticiais.html", tipo:"ATS/ERS e Fleischner", area:"pneumo", min:20,
  t:"Doenças intersticiais e o nódulo pulmonar",
  s:"Crepitação em velcro e difusão baixa, o padrão que dispensa biópsia, o corticoide que aumentou mortalidade na fibrose idiopática, fenótipo progressivo e o seguimento do nódulo incidental."},
 {f:"hipertensao-pulmonar-sono.html", tipo:"ESC/ERS 2022 e AASM", area:"pneumo", min:19,
  t:"Hipertensão pulmonar e distúrbios respiratórios do sono",
  s:"A pressão de oclusão que separa grupo 1 de grupo 2, a cintilografia V/Q que a angiotomografia não substitui, a única forma curável, CPAP e o oxigênio que piora a hipoventilação."},
 {f:"derrame-pleural.html", tipo:"BTS 2023 e ATS/STS/STR", area:"pneumo", min:24,
  t:"Derrame pleural e doenças da pleura",
  s:"Quem não precisa de punção, os critérios de Light e o gradiente de albumina que os corrige, o pH que indica dreno antes do pus, a ADA do exsudato linfocítico e o pulmão encarcerado."},
 {f:"tosse-cronica-e-bronquiectasias.html", tipo:"CHEST, ERS e SBPT", area:"pneumo", min:24,
  t:"Tosse crônica e bronquiectasias",
  s:"As três grandes causas testadas na ordem certa, o inibidor da ECA que começa meses depois, a tosse por hipersensibilidade e a bronquiectasia que nunca é diagnóstico final."},
 {f:"prova-de-funcao-pulmonar.html", tipo:"ATS/ERS 2022 e SBPT", area:"pneumo", min:20,
  t:"Interpretar a prova de função pulmonar",
  s:"O exame que não se interpreta se foi mal feito, o limite inferior que substituiu o 0,70 fixo, a restrição que a espirometria só sugere, a difusão que abre o diagnóstico e as alças que localizam a obstrução."},

 {grupo:"Infectologia", sub:"o que é competência do clínico"},
 {f:"hiv.html", tipo:"PCDT do MS", area:"infecto", min:21,
  t:"HIV: tratar todos, no mesmo dia, e o que rastrear conforme o CD4",
  s:"As duas exclusões antes do início imediato, indetectável igual a intransmissível, as profilaxias por faixa de CD4, a pressão de abertura na criptococose e o tempo do antirretroviral na tuberculose."},
 {f:"tuberculose.html", tipo:"Manual do MS", area:"infecto", min:19,
  t:"Tuberculose: do sintomático respiratório à hepatotoxicidade",
  s:"O teste rápido molecular como primeiro exame, o esquema básico e as fases, quando suspender e como reintroduzir de forma escalonada, e quem trata infecção latente."},
 {f:"antimicrobianos.html", tipo:"IDSA e ANVISA", area:"infecto", min:18,
  t:"Antimicrobianos: escolher, descalonar e parar",
  s:"Colonização não é infecção, a tabela de espectro e de resistência, os cursos curtos que igualam os longos, a desrotulação da alergia à penicilina e a profilaxia cirúrgica que termina na sala."},
 {f:"dengue.html", tipo:"Manual do MS 2024", area:"infecto", min:12,
  t:"Dengue: a fase crítica começa quando a febre cede",
  s:"Grupos A a D, os sete sinais de alarme e os volumes exatos — 10 mL/kg na primeira hora no grupo C, 20 mL/kg em 20 minutos no D, começando onde o paciente estiver."},
 {f:"febre-origem-indeterminada.html", tipo:"ESC 2023 e IDSA", area:"infecto", min:20,
  t:"Febre de origem indeterminada e endocardite",
  s:"As quatro grandes causas e o roteiro em etapas, por que não tratar às cegas, três pares de hemocultura antes do antibiótico, os critérios de Duke de 2023 e quando operar."},
 {f:"infeccoes-tropicais.html", tipo:"Ministério da Saúde e OPAS", area:"infecto", min:24,
  t:"Arboviroses, malária e endemias brasileiras",
  s:"O estadiamento A-B-C-D da dengue e a hidratação de cada grupo, a malária que agrava em horas, leptospirose com hemorragia alveolar, Chagas oral, calazar e febre maculosa."},
 {f:"meningites-e-encefalites.html", tipo:"IDSA, ESCMID e Ministério da Saúde", area:"infecto", min:24,
  t:"Meningites e encefalites",
  s:"Quem faz tomografia antes da punção e por que ela nunca atrasa o antibiótico, a ampicilina que se esquece, a dexametasona antes da primeira dose e o aciclovir que não espera a PCR."},
 {f:"infeccoes-hospitalares.html", tipo:"ANVISA, IDSA/SHEA e OMS", area:"infecto", min:24,
  t:"Infecções relacionadas à assistência e multirresistência",
  s:"A pergunta diária sobre cada dispositivo, a bacteriúria que não se trata, o cateter que sai no <i>S. aureus</i>, os mecanismos de resistência e as durações curtas que bastam."},
 {f:"vacinacao-do-adulto.html", tipo:"PNI/Ministério da Saúde e SBIm", area:"infecto", min:25,
  t:"Vacinação do adulto e profilaxias pós-exposição",
  s:"As cinco regras que resolvem quase tudo, a janela antes do imunobiológico, a tabela do tétano, a mordida que pede observação em vez de soro e as 72 horas da profilaxia do HIV."},
 {f:"ist.html", tipo:"PCDT-IST 2022 e CDC 2021", area:"infecto", min:23,
  t:"Infecções sexualmente transmissíveis",
  s:"A abordagem sindrômica das úlceras e corrimentos, o VDRL que acompanha e o treponêmico que não, a dessensibilização da gestante, a DIP de limiar baixo e a prevenção combinada."},

 {grupo:"Neurologia", sub:"as decisões com relógio"},
 {f:"avc-isquemico.html", tipo:"AHA/ASA 2026", area:"neuro", min:11,
  t:"AVC isquêmico agudo: a janela e as decisões",
  s:"Tenecteplase como alternativa plena, o que fazer com NIHSS baixo, o AVC ao despertar e os limites de pressão antes de trombolisar."},
 {f:"epilepsia.html", tipo:"ILAE e NCS/AES", area:"neuro", min:20,
  t:"Crise convulsiva e estado de mal: o relógio dos cinco minutos",
  s:"A subdose do benzodiazepínico que define o desfecho, o algoritmo por tempo, o estado de mal não convulsivo que se disfarça de pós-ictal e o valproato na mulher em idade fértil."},
 {f:"cefaleias.html", tipo:"ICHD-3 e AHS", area:"neuro", min:20,
  t:"Cefaleias: separar a primária da que mata",
  s:"Os sinais de alarme, a cefaleia em trovoada com tomografia normal, a aura que contraindica o contraceptivo combinado, a profilaxia a partir de 4 dias e a cefaleia por uso excessivo."},
 {f:"demencias-parkinson.html", tipo:"NIA-AA, MDS e ABN", area:"neuro", min:21,
  t:"Demências e parkinsonismos: reconhecer o padrão antes de tratar",
  s:"As causas reversíveis, a hipersensibilidade a neurolépticos nos corpos de Lewy, a hidrocefalia de pressão normal, o parkinsonismo medicamentoso e as neuropatias periféricas."},
 {f:"coma-e-hipertensao-intracraniana.html", tipo:"Neurocritical Care Society e CFM 2.173/2017", area:"neuro", min:23,
  t:"Coma e hipertensão intracraniana",
  s:"Os reflexos de tronco que separam estrutural de metabólico, as síndromes de herniação, o escalonamento da hipertensão intracraniana, quem faz tomografia antes da punção e a morte encefálica."},
 {f:"doencas-neuromusculares.html", tipo:"AAN, EFNS e ABN", area:"neuro", min:22,
  t:"Neuropatias e doenças neuromusculares",
  s:"Os quatro andares da fraqueza, a capacidade vital que substitui a oximetria, Guillain-Barré sem corticoide, o timoma da miastenia e os antibióticos que precipitam crise."},
 {f:"tontura-e-vertigem.html", tipo:"AAN/AHA e Bárány Society", area:"neuro", min:23,
  t:"Tontura e vertigem no pronto-socorro",
  s:"Trocar a pergunta pela do padrão temporal, o HINTS que supera a ressonância nas primeiras horas, o impulso cefálico normal que assusta, a manobra que trata a VPPB e os sedativos que atrapalham."},
 {f:"esclerose-multipla.html", tipo:"McDonald 2024 e PCDT/MS", area:"neuro", min:24,
  t:"Esclerose múltipla e doenças desmielinizantes",
  s:"Uhthoff e Lhermitte, a disseminação no tempo e no espaço, o pseudossurto que não é surto, o risco de leucoencefalopatia no natalizumabe e a neuromielite que piora com o tratamento da esclerose."},

 {grupo:"Nefrologia", sub:"aguda e crônica"},
 {f:"eletrolitos.html", tipo:"Abordagem sistemática", area:"nefro", min:16,
  t:"Distúrbios hidroeletrolíticos e ácido-base",
  s:"Ler a gasometria em seis passos, o delta-delta que revela o distúrbio triplo, o cloro urinário na alcalose, os limites de correção do sódio e a sequência da hipercalemia."},
 {f:"lesao-renal-aguda.html", tipo:"KDIGO", area:"nefro", min:19,
  t:"Lesão renal aguda: as três perguntas e as cinco indicações de diálise",
  s:"Pré-renal, renal ou pós-renal; o sedimento e os índices que enganam sob diurético; a tríplice ameaça; e por que diurético e dopamina não tratam."},
 {f:"drc.html", tipo:"KDIGO 2024", area:"nefro", min:19,
  t:"Doença renal crônica: a albuminúria é metade do diagnóstico",
  s:"A classificação em duas dimensões, os pilares que reduzem progressão, a elevação esperada de 30% da creatinina, o alvo restrito de hemoglobina e o preparo precoce para diálise."},
 {f:"glomerulopatias.html", tipo:"KDIGO 2021/2024", area:"nefro", min:18,
  t:"Glomerulopatias: nefrítica, nefrótica e a que corre",
  s:"O sedimento urinário que fecha o diagnóstico, o diferencial pelo complemento, a rapidamente progressiva como emergência e as indicações de biópsia."},
 {f:"nefrolitiase-itu.html", tipo:"EAU, AUA e IDSA", area:"nefro", min:18,
  t:"Litíase urinária e infecção do trato urinário",
  s:"Cólica renal e terapia expulsiva, obstrução com infecção = drenagem de urgência, os tipos de cálculo e a bacteriúria assintomática que não se trata."},
 {f:"dialise-e-transplante.html", tipo:"KDIGO e SBN", area:"nefro", min:24,
  t:"Diálise e transplante renal para o clínico",
  s:"As cinco indicações de urgência dialítica, o braço da fístula que ninguém toca, as complicações intradialíticas, a peritonite do efluente turvo e as interações que custam o enxerto."},
 {f:"rim-e-farmacos.html", tipo:"KDIGO e Beers 2023", area:"nefro", min:24,
  t:"Rim e fármacos: nefrotoxicidade e ajuste de dose",
  s:"A trinca que derruba a filtração, a creatinina que sobe sem lesão, os 30% esperados do inibidor da ECA, o contraste superestimado e a nefrite intersticial sem febre nem rash."},
 {f:"rim-nas-doencas-sistemicas.html", tipo:"KDIGO 2021/2024 e consensos", area:"nefro", min:24,
  t:"O rim nas doenças sistêmicas e nas doenças hereditárias",
  s:"A fita que não detecta cadeia leve, a glomerulonefrite que não espera o ANCA, as microangiopatias que se separam pelo tratamento, o policístico e a obstrução que ninguém lembra."},

 {grupo:"Gastroenterologia e hepatologia", sub:"do sangramento ao fígado"},
 {f:"cirrose.html", tipo:"Baveno VII e EASL", area:"gastro", min:15,
  t:"Cirrose descompensada: as cinco complicações que matam",
  s:"A regra dos 5 da elastografia, o pacote da hemorragia varicosa, os 250 neutrófilos da peritonite, a albumina que reduz mortalidade e por que dosar amônia não ajuda."},
 {f:"hemorragia-digestiva.html", tipo:"ESGE, ACG e Baveno VII", area:"gastro", min:17,
  t:"Hemorragia digestiva: estabilizar, estratificar, endoscopar",
  s:"Por que transfundir menos, a hematoquezia que é sangramento alto, a classificação de Forrest e o antibiótico no cirrótico que reduz mortalidade tanto quanto a endoscopia."},
 {f:"pancreatite-vias-biliares.html", tipo:"AGA e Tokyo Guidelines", area:"gastro", min:18,
  t:"Pancreatite e vias biliares: o que decide nas primeiras 24 horas",
  s:"Nutrição enteral precoce, nenhum antibiótico profilático, colecistectomia na mesma internação — e a colangite obstrutiva que exige drenagem, não só antibiótico."},
 {f:"dii.html", tipo:"ECCO e AGA", area:"gastro", min:17,
  t:"Doenças inflamatórias intestinais: Crohn e retocolite",
  s:"O corticoide que induz mas nunca mantém, os critérios de Truelove e Witts, a profilaxia de trombose com sangramento intestinal e a estenose fibrótica que não responde a biológico."},
 {f:"hepatites-masld.html", tipo:"PCDT do MS, EASL e AASLD", area:"gastro", min:20,
  t:"Hepatites virais e doença hepática esteatótica metabólica",
  s:"Ler a sorologia da hepatite B, o anti-HBc que ninguém pede antes do rituximabe, a hepatite C curável em 8 a 12 semanas e a MASLD em que o que importa é a fibrose."},
 {f:"disfagia-esofago.html", tipo:"ACG e Chicago 4.0", area:"gastro", min:20,
  t:"Disfagia, refluxo e doenças do esôfago",
  s:"Orofaríngea × esofágica, o padrão que aponta a causa, o inibidor de bomba tomado na hora certa, o Barrett e sua vigilância, esofagite eosinofílica e acalasia."},
 {f:"diarreia-ma-absorcao.html", tipo:"ACG e AGA", area:"gastro", min:21,
  t:"Diarreia crônica e síndromes de má absorção",
  s:"Aquosa, gordurosa ou inflamatória; a diarreia noturna que muda tudo; celíaca que se esconde na anemia; colite microscópica na biópsia de mucosa normal; e os sais biliares esquecidos."},

 {grupo:"Oncologia", sub:"reconhecer e rastrear"},
 {f:"emergencias-oncologicas.html", tipo:"ASCO, ESMO e NCCN", area:"onco", min:21,
  t:"Emergências oncológicas: as sete que não podem esperar o oncologista",
  s:"A primeira hora da neutropenia febril, a compressão medular cujo prognóstico é o estado neurológico agora, a lise tumoral e a toxicidade da imunoterapia, que se trata com imunossupressão."},
 {f:"rastreamento-cancer.html", tipo:"INCA e USPSTF", area:"onco", min:21,
  t:"Rastreamento de câncer: o que o Brasil recomenda e por que difere",
  s:"Os três vieses que fazem o rastreio parecer melhor do que é, a divergência entre INCA e sociedades na mama, a decisão compartilhada na próstata e quando parar de rastrear."},
 {f:"toxicidade-oncologica.html", tipo:"ASCO, NCCN e ESMO", area:"onco", min:24,
  t:"Toxicidade do tratamento oncológico",
  s:"A regra da primeira hora na neutropenia febril, o esquema quádruplo da êmese, a toxicidade imunomediada órgão a órgão, a hipofisite que se repõe na ordem certa e a miocardite por checkpoint."},
 {f:"canceres-mais-comuns.html", tipo:"INCA, NCCN e ESMO", area:"onco", min:25,
  t:"Os cânceres mais comuns: o que cabe ao clínico",
  s:"Anemia ferropriva que é câncer de cólon, mamografia normal que não exclui nódulo palpável, painel molecular no adenocarcinoma pulmonar, marcador tumoral que não diagnostica e os prazos da lei."},

 {grupo:"Geriatria e cuidados paliativos", sub:"o idoso não se apresenta pelo órgão"},
 {f:"sindromes-geriatricas.html", tipo:"AGS e World Falls Guidelines", area:"geriatria", min:21,
  t:"Síndromes geriátricas: os cinco is e a avaliação que muda conduta",
  s:"As atividades instrumentais que falham primeiro, a avaliação multifatorial das quedas, o delirium hipoativo, a cascata de prescrição e as metas terapêuticas do idoso frágil."},
 {f:"paliativos.html", tipo:"CFM e OMS", area:"geriatria", min:18,
  t:"Cuidados paliativos: decisões que o clínico toma",
  s:"A pergunta surpresa, o protocolo de má notícia em seis passos, a escada analgésica com rotação de opioide, o opioide na dispneia e as distinções entre ortotanásia, distanásia e eutanásia."},
 {f:"polifarmacia-desprescricao.html", tipo:"Beers 2023 e STOPP/START v3", area:"geriatria", min:22,
  t:"Polifarmácia e desprescrição",
  s:"A cascata iatrogênica em seis exemplos, a creatinina normal que esconde rim ruim, a carga anticolinérgica somada, o método de desprescrever e as retiradas que exigem desmame."},
 {f:"idoso-hospitalizado.html", tipo:"NICE, AGS e Ministério da Saúde", area:"geriatria", min:23,
  t:"O idoso hospitalizado",
  s:"O declínio funcional como desfecho invisível, o delirium hipoativo que ninguém vê, a sonda que não previne aspiração na demência, a diarreia que é fecaloma e a alta que precisa reconciliar."},

 {grupo:"Psiquiatria e dermatologia na clínica", sub:"as duas que o clínico resolve"},
 {f:"depressao-ansiedade.html", tipo:"APA, NICE e MS", area:"psiq", min:23,
  t:"Depressão, ansiedade e risco de suicídio no consultório do clínico",
  s:"A pergunta sobre mania antes de todo antidepressivo, escolher o fármaco pelo perfil, perguntar sobre suicídio não induz, e a desprescrição do benzodiazepínico no idoso."},
 {f:"psicose-agitacao-substancias.html", tipo:"Project BETA e APA", area:"psiq", min:22,
  t:"Psicose, agitação e substâncias: a emergência psiquiátrica é clínica até prova em contrário",
  s:"As bandeiras vermelhas de causa orgânica, o desescalonamento antes da contenção, síndrome neuroléptica maligna × serotoninérgica, o lítio e a abstinência alcoólica."},
 {f:"derma-clinica.html", tipo:"Consensos internacionais", area:"derma", min:21,
  t:"Dermatologia para o clínico: a pele que anuncia doença grave",
  s:"Os sinais que separam o exantema banal da farmacodermia que mata, DRESS e necrólise epidérmica, a pele como sinal de doença sistêmica, as úlceras de membros e a lesão pigmentada."},
 {f:"farmacodermias-graves.html", tipo:"SBD e RegiSCAR", area:"derma", min:23,
  t:"Farmacodermias graves",
  s:"As bandeiras vermelhas que tiram o caso do rótulo de exantema benigno, a latência que aponta o culpado, DRESS e sua recidiva no desmame rápido, Stevens-Johnson e o angioedema por inibidor da ECA."},
 {f:"dermatoses-comuns.html", tipo:"SBD e IDSA", area:"derma", min:22,
  t:"Dermatoses comuns no consultório do clínico",
  s:"A celulite que é dermatite de estase, a dor desproporcional da fasciíte, a tinha incógnita criada pelo corticoide, a escabiose que exige tratar a casa e como prescrever corticoide tópico."},
 {f:"bipolar-e-psicofarmacos.html", tipo:"CANMAT/ISBD e APA", area:"psiq", min:23,
  t:"Transtorno bipolar e psicofármacos na clínica",
  s:"A hipomania que ninguém relata, o antidepressivo isolado que vira mania, o que sobe a litemia, a titulação da lamotrigina e o clônus que separa serotoninérgica de neuroléptica maligna."},
 {f:"insonia-e-sono.html", tipo:"AASM e ICSD-3", area:"psiq", min:22,
  t:"Insônia e outros transtornos do sono",
  s:"A terapia cognitivo-comportamental como primeira linha, a restrição de tempo na cama, a insônia refratária que é apneia, a ferritina das pernas inquietas e o REM que anuncia sinucleinopatia."},

 {grupo:"SUS, ética e epidemiologia", sub:"o que cai e quase ninguém estuda"},
 {f:"sus-principios.html", tipo:"Lei 8.080, PNAB e MS", area:"sus", min:21,
  t:"SUS: os princípios, a atenção primária e os números que a prova cobra",
  s:"Princípios e legislação, os quatro atributos da atenção primária, notificação compulsória — e epidemiologia clínica em uma página: sensibilidade, valor preditivo, NNT e intervalo de confiança."},
 {f:"etica-medica.html", tipo:"CFM e legislação", area:"sus", min:21,
  t:"Ética médica: sigilo, consentimento, documentos e o fim da vida",
  s:"Quem decide, o que pode ser dito, o que se assina — atestado, prontuário, declaração de óbito — e as distinções entre ortotanásia, distanásia, eutanásia e sedação paliativa."},

 {grupo:"Doenças raras", sub:"individualmente raras, coletivamente comuns"},
 {f:"raras-abordagem.html", tipo:"Política Nacional e ACMG", area:"sus", min:21,
  t:"Doenças raras: quando o clínico deve desconfiar",
  s:"As sete bandeiras vermelhas, os padrões clínicos que se repetem, o heredograma de três gerações, a variante de significado incerto que não é diagnóstico e as raras que têm tratamento."},
 {f:"raras-deposito-metabolicas.html", tipo:"PCDT e consensos", area:"endocrino", min:23,
  t:"Doenças de depósito e metabólicas do adulto",
  s:"Fabry, Gaucher, Pompe tardia, Wilson, hemocromatose, alfa-1-antitripsina, porfirias, homocistinúria e mitocondriais — cada uma com o exame que diagnostica e o erro que se comete."},
 {f:"raras-sistemicas.html", tipo:"Consensos internacionais", area:"reumato", min:25,
  t:"Raras sistêmicas: amiloidose, sarcoidose, IgG4, HLH e as febres periódicas",
  s:"Tipar o amiloide antes de tratar, a sarcoidose que nem sempre se trata, a IgG4 que imita câncer, a ferritina acima de 10.000 que é HLH, Behçet, mastocitose e imunodeficiência do adulto."}
];
